modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.overshock.games"
logoFile="logo.png"
authors="Overshock Games"
description="Explore the Corruption and fight the Null!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.eternull]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eternull]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"



